### ISSUE TITLE
Blank screen of death on clean install of Omeka 2.5

### ISSUE THREAD

**Issue by sooyhwang** [UCSCLibrary/CdmLink#5]
I just installed Omeka 2.5 and the first thing I did was to install CdmLink. But once I "install"ed it on the plugin page, omeka only shows blank screens of death. The main site, admin settings page, and everything else are simply blank pages. If I remove the CdmLink directory from the plugins folder, omeka site is back to normal (although the plugin page would complain about missing CdmLink plugin. So I guess the install went through, but something is crashing the site.) What would be causing this crash?

Here's the server info:
Ubuntu 16.04.1 LTS
Apache/2.4.18 (Ubuntu)
PHP Version 7.0.13-0ubuntu0.16.04.1
mysql  Ver 15.1 Distrib 10.0.29-MariaDB

Thank you for your assistance in advance.

**Comment by NedHenry** [comment]
Thanks for this report! I really appreciate your feedback. We haven't
actually tested the CdmLink plugin on Omeka 2.5, and the new Omeka version
probably requires a few changes to the plugin. We can definitely update the
plugin to work with Omeka 2.5. I would estimate that this will happen in
the next few weeks or month. For now, the CdmLink plugin should still work
on Omeka 2.4.
Best,
Ned

**Comment by sooyhwang** [comment]
Thanks for the quick reply, but it doesn't look like the Omeka version issue. I tried a clean install of 2.4 (dropped all the tables in the omeka DB as well so it was a clean install) but am having the same blank screen of death problem as soon as I install the CdmLink plugin.

**Comment by NedHenry** [comment]
Good to know, thanks for that information. In that case, I am not sure what
the problem is and I will have to investigate. I will let you know when we
have more information.

**Comment by sooyhwang** [comment]
Could you tell me the PHP version of a working environment? That's the immediate culprit I could think of.

**Comment by NedHenry** [comment]
I am using PHP 5.3.3. I'll let you know when I have a chance to look into
it more thoroughly.

**Comment by sooyhwang** [comment]
Just tried PHP 5.6 with Omeka 2.4, but no luck :(
PHP Version 5.6.30-1+deb.sury.org~xenial+1

**Comment by sooyhwang** [comment]
I reverted to PHP7 and Omeka 2.5. I tried installing CSV Import and it installed fine, so other plugins seem to be working. I uncommented error reporting in Omeka .htaccess and it's showing this error message on the browser screen:

Fatal error: Class 'Omeka_plugin_AbstractPlugin' not found in /var/www/html/omeka/plugins/CdmLink/CdmLinkPlugin.php on line 15

Hopefully this helps troubleshooting. Thanks!

**Comment by sooyhwang** [comment]
As per this,
https://forum.omeka.org/t/omeka-plugin-abstractplugin-not-found-error/2777

I edited the CdmLinkPlugin.php file and changed Omeka_plugin_AbstractPlugin to Omeka_Plugin_AbstractPlugin, and there is no more crash! Hooray!

You may want to update the repository with the correct case P.

**Comment by NedHenry** [comment]
I fixed this typo in a quick commit: 244f2796ded4c619b000be137e1ca018ee3edcd9
We have not had development hours to maintain this plugin in some time, but we hope to update it in the next few weeks.

**Comment by NedHenry** [comment]
While this does appear to be the accepted syntax, I was unable to recreate the bug with the old syntax. I was unable to get the plugin to fail regardless of the capitalization here.
